### ISSUE TITLE
The 'packaging' distribution was not found and is required by Sphinx

### ISSUE THREAD

**Issue by pawosm-arm** [luliu/swift-overlay#1]
I've made the very first attempt to build this, and it failed as such:

```
[409/1133][ 36%][812.975s] Building HTML documentation
FAILED: docs/CMakeFiles/docs_html
cd /var/tmp/portage/dev-lang/swift-5.4/work/swift/docs && /usr/bin/sphinx-build -W -D latex_elements.papersize=letter -d /var/tmp/portage/dev-lang/swift-5.4/work/build/Ninja-ReleaseAssert/swift-linux-aarch64/doctrees -b html . /var/tmp/portage/dev-lang/swift-5.4/work/build/Ninja-ReleaseAssert/swift-linux-aarch64/docs/html
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.7/sphinx-build", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3238, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 567, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 884, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 770, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'packaging' distribution was not found and is required by Sphinx
```
I'm not familiar with Sphinx, does it need to have some companion package installed?

**Comment by pawosm-arm** [comment]
Blah, there's something I've just noticed. The default python version on this system is 3.8, yet somehow the log above refers to python 3.7. I don't have dev-python/packaging built for python 3.7, it's been built for 3.8 only. I guess I need to rebuild it for both.
